apiVersion: v1
kind: ServiceAccount
metadata:
  name: xiong-go-client-test
  namespace: sample
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xiong-go-client-test-role
rules:
  - apiGroups: ['']
    resources: ['pods', 'configmaps']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get']
  - apiGroups: ['networking.k8s.io', 'extensions']
    resources: ['ingresses']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xiong-go-client-test-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xiong-go-client-test-role
subjects:
  - kind: ServiceAccount
    name: xiong-go-client-test
    namespace: sample
